Movie-Repo/Models/ErrorViewModel.cs
using System;

namespace Movie_Repo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Movie-Repo/Models/MasterMovie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Movie_Repo.Models
{
    public class MasterMovie
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string ImgLink { get; set; }

        public string Time { get; set; }

        public string Date { get; set; }

        public int Fk_TypeId { get; set; }
    }
}

Movie-Repo/Models/MasterType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Movie_Repo.Models
{
    public class MasterType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Movie-Repo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Movie_Repo.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Movie_Repo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Movie-Repo/Controllers/MasterMovieController.cs
using Microsoft.AspNetCore.Mvc;
using Movie_Repo.Models;
using Movie_Repo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Movie_Repo.Controllers
{
    public class MasterMovieController : Controller
    {
        private readonly IMasterMovieService _masterMovieService;

        public MasterMovieController(IMasterMovieService masterMovieService)
        {
            _masterMovieService = masterMovieService;
        }

        // GET: MasterMovieController
        public ActionResult Index()
        {
            var movies = _masterMovieService.GetAll();
            return View(movies);
        }

        // GET: MasterMovieController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterMovieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterMovie item)
        {
            if (ModelState.IsValid)
            {
                _masterMovieService.AddMovie(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: MasterMovieController/Edit/5
        public ActionResult Edit(int id)
        {
            MasterMovie item = _masterMovieService.GetById(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: MasterMovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterMovie item)
        {
            if (ModelState.IsValid)
            {
                _masterMovieService.UpdateMovie(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // POST: MasterMovieController/Delete/5
        public ActionResult Delete(int id)
        {
            _masterMovieService.DeleteMovie(id);
            return RedirectToAction("Index");
        }
    }
}

Movie-Repo/Controllers/MasterTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Movie_Repo.Models;
using Movie_Repo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Movie_Repo.Controllers
{
    public class MasterTypeController : Controller
    {
        private readonly IMasterTypeService _masterTypeService;

        public MasterTypeController(IMasterTypeService masterTypeService)
        {
            _masterTypeService = masterTypeService;
        }

        // GET: MasterTypeController
        public ActionResult Index()
        {
            var Types = _masterTypeService.GetAll();
            return View(Types);
        }

        // GET: MasterTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MasterTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterType item)
        {
            if (ModelState.IsValid)
            {
                _masterTypeService.AddType(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: MasterTypeController/Edit/5
        public ActionResult Edit(int id)
        {
            MasterType item = _masterTypeService.GetById(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: MasterTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterType item)
        {
            if (ModelState.IsValid)
            {
                _masterTypeService.UpdateType(item);
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // POST: MasterTypeController/Delete/5
        public ActionResult Delete(int id)
        {
            _masterTypeService.DeleteType(id);
            return RedirectToAction("Index");
        }
    }
}

Movie-Repo/Views/MasterMovie/Create.cshtml
@model Movie_Repo.Models.MasterMovie

@{
    ViewData["Title"] = "Create";
}
<body>
    <h1>Create</h1>

    <h4>MasterMovie</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*<div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>*@
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImgLink" class="control-label"></label>
                    <input asp-for="ImgLink" class="form-control" />
                    <span asp-validation-for="ImgLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Time" class="control-label"></label>
                    <input asp-for="Time" class="form-control" />
                    <span asp-validation-for="Time" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Fk_TypeId" class="control-label"></label>
                    <input asp-for="Fk_TypeId" class="form-control" />
                    <span asp-validation-for="Fk_TypeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Movie-Repo/Views/MasterMovie/Edit.cshtml
@model Movie_Repo.Models.MasterMovie

@{
    ViewData["Title"] = "Edit";
}
<body>
    <h1>Edit</h1>

    <h4>MasterMovie</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*<div class="form-group">
                        <label asp-for="Id" class="control-label"></label>
                        <input asp-for="Id" class="form-control" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>*@
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImgLink" class="control-label"></label>
                    <input asp-for="ImgLink" class="form-control" />
                    <span asp-validation-for="ImgLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Time" class="control-label"></label>
                    <input asp-for="Time" class="form-control" />
                    <span asp-validation-for="Time" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Fk_TypeId" class="control-label"></label>
                    <input asp-for="Fk_TypeId" class="form-control" />
                    <span asp-validation-for="Fk_TypeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Movie-Repo/Views/MasterMovie/Index.cshtml
@model IEnumerable<Movie_Repo.Models.MasterMovie>

@{
    ViewData["Title"] = "Index";
}

<h1>Movies</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImgLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fk_TypeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <img style="width:150px; height:150px;" src="@Url.Content(item.ImgLink)" alt="IMAGES" />
                @*@Html.DisplayFor(modelItem => item.ImgLink)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fk_TypeId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Movie-Repo/Views/MasterType/Create.cshtml
@model Movie_Repo.Models.MasterType

@{
    ViewData["Title"] = "Create";
}
<body>
    <h1>Create</h1>

    <h4>Movie Type</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Movie-Repo/Views/MasterType/Edit.cshtml
@model Movie_Repo.Models.MasterType

@{
    ViewData["Title"] = "Edit";
}
<body>
    <h1>Edit</h1>

    <h4>MasterMovie</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Movie-Repo/Views/MasterType/Index.cshtml
@model IEnumerable<Movie_Repo.Models.MasterType>

@{
    ViewData["Title"] = "Index";
}

<h1>Movie Types</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Movie-Repo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.1.0/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/AdminLTE-3.1.0/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.1.0/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.1.0/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
         with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a href="@Url.Action("Index","Home")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Home
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","MasterMovie")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Movies
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","MasterType")" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Movie Type
                                </p>
                            </a>
                        </li>



                        <li class="nav-header">Admin</li>

                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Gallery
                                </p>
                            </a>
                        </li>







                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col">
                            @RenderBody()

                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">

                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.1.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.1.0/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/AdminLTE-3.1.0/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/AdminLTE-3.1.0/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/AdminLTE-3.1.0/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/AdminLTE-3.1.0/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/AdminLTE-3.1.0/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/AdminLTE-3.1.0/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/AdminLTE-3.1.0/plugins/moment/moment.min.js"></script>
    <script src="~/AdminLTE-3.1.0/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/AdminLTE-3.1.0/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.1.0/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/AdminLTE-3.1.0/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.1.0/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.1.0/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/AdminLTE-3.1.0/dist/js/pages/dashboard.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>